version: '3.7'
services:
  db:
    image: postgres:12
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password123
  graphql:
    build:
      context: backend
    ports:
      - "4000:4000"
      - "2222:22"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      ENABLE_SSH: "false"
      DATABASE_URL: postgres://postgres:password123@db/${DBNAME}?sslmode=disable
      JWT_SECRET: AVerySecretString
      PGPASSWORD: password123
      DBNAME: "$DBNAME"
    depends_on:
      - db
    links:
      - db
  frontend:
    build:
      context: meal-planner-fredericton-ui
    ports:
      - "3000:3000"
    volumes:
      - ./meal-planner-fredericton-ui:/app
      - /app/node_modules
    environment:
      DATABASE_URL: postgres://postgres:password123@db/${DBNAME}?sslmode=disable
      JWT_SECRET: AVerySecretString
      PGPASSWORD: password123
      DBNAME: "$DBNAME"
    depends_on:
      - graphql
    links:
      - graphql

volumes:
  pgdata:
